### PR TITLE
Adds field for alternate lookup if AD domain is not the same as email domain

### PR DESCRIPTION
**Pull request by lfarrell**
@kloor I've created a field called alternateDomainName that will be used for email address lookups if a value is provided. It may be a tad clunky as it's stripped out of the Zend Ldap options processed by Zend since it's not a valid Zend Ldap option and then looked up via get_option in the authenticate() method in your CentralAuth_LdapAdapter class.

Thanks for a useful plugin,

Dean

### CODE REVIEW

**Comment by kloor** [comment]
Thanks for the pull request. I'm not going to merge it as-is due to the whitespace changes, which make reviewing code history difficult.

I'm also not certain I want the plugin to use the accountDomainName if the alternativeDomainName is not specified. It think the configuration would be more straightforward if the domain used to match an email address in Omeka was configured apart from the LDAP settings, so I'm planning on combining this new field with the CAS/SSO field for email domain.

**Comment by lfarrell** [comment]
Sorry about the whitespace issue. Not sure what happened there.  It does make more sense outside LDAP since it's not really a valid Zend Ldap option

**Comment by kloor** [comment]
I've just pushed an update that now has a new option to choose between matching the Omeka user database via username or email, and add a standard field for email domain that both the CAS and LDAP authentication uses. 

There are still a few other changes I want to make to the plugin before I package a new release, but feel free to give the changes a try and let me know if there was anything I overlooked.

**Comment by kloor** [comment]
I've packaged a new release with the change listed above.

**Pull request closed without merging**
